### ISSUE TITLE
[BUG] Events.mat File generation 

### ISSUE THREAD

**Issue by Zak-Eckert** [S-Belanger/Umit#39]
Greetings, 
I have encountered a bug which seems to be present with the run_ImagesClassification function. 

Upon launching a pipeline using umIToolbox, I was unable to generate event triggered analysis due to a bug in the run_ImagesClassification function. It appears that it was unable to generate an event.mat file, where as a result, the later steps in a pipeline (such as calculate_DF_F_byEvent) are unable to properly execute their role. See error in run_ImagesClassification function below: 

**************************
No Stimulations detected. Resting State experiment?
Sorting images per channels.
Sorting img_00000.bin.
Sorting img_00001.bin.
Sorting img_00002.bin.
Sorting img_00003.bin.
Done.
Warning: Stim signal not found! Skipped Event file creation. <-- This appears to be where the issue lies 

It appears that the function is just unable to read the triggers, although they were there. 
I was hoping that this could be looked into so I could proceed with my work! 
Thank you!

Zachary Eckert

**Comment by BrunoOFSouza** [comment]
Fixed in commit f28f6d341556ca375820e2b90611f44ac53723d3.
We included a new parameter to the function `run_ImagesClassification`.
Now, you can select the analog IN channel containing the triggers. There are two internal channels (main and aux) and eight external ones (AI1-8). In your case, the triggers are located in the internal-Aux channel.

Please, note that changes were applied to the ***IOI_ana*** library as well. So, to make it work, update this toolbox and the library at [https://github.com/flesage/ioi_ana](https://github.com/flesage/ioi_ana)
